<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZxnRpP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZxnRpP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXZxnRpP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXZxnRpP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXZxnRpP\App_KernelDevDebugContainer([
    'container.build_hash' => 'XZxnRpP',
    'container.build_id' => '17d5230f',
    'container.build_time' => 1768558060,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZxnRpP');
